var data = {
	"ad":"Ancient Darkspawn",
	"aeg":"Arl Eamon Guerrin",
	"ag":"Arlathan General",
	"ah":"Arcane Horror",
	"aj":"Apostate Jowan",
	"aoe":"area-of-effect attack",
	"archie":"The Architect",
	"arw":"Ancient Rock Wraith",
	"aw":["Alamarri Warlord","Alpha Werewolf","Ash Wraith","Alpha Wolf"],
	"atc":"Ancient Thaig Challenge",
	"av":"Aveline Vallen",
	"bark":"Barkspawn",
	"barkie":"Barkspawn",
	"barky":"Barkspawn",
	"bd":"Brogan Dace",
	"ben":"Ben-Hassrath",
	"bh":"Ben-Hassrath",
	"bm":"Brood Mother",
	"boobs":"Brood Mother",
	"bm":["Blood Mage", "Brood Mother"],
	"cal":"Caladrius",
	"capt. isa":"Captain Isabela",
	"cb":"Common Bear",
	"cg":["Chasind General", "Capital Games"],
	"cory":"Corypheus",
	"cs":"Charred Sylvan",
	"csq":"Corrupted Spider Queen",
	"dan":"Danarius",
	"danny":"Danarius",
	"daw":"Dalish Arcane Warrior",
	"dd":"Desire Demon",
	"df":"Dragon Flemeth",
	"dp":"Duke Prosper",
	"ds":"Diamond Shale",
	"dw":"Dalish Warrior",
	"ea":"Electronic Arts (the publisher of the Dragon Age games)",
	"ec":"Eluvian Challenge (Map #15)",
	"eh":"Elite Harlequin",
	"faw":"Fereldan Ash Warrior",
	"feo":"First Enchanter Orsino",
	"ff":"Fereldan Frostback",
	"fk":"Fereldan Knight",
	"fiona":"Grand Enchanter Fiona",
	"flem":"Flemeth",
	"gca":"Guard Captain Aveline",
	"gef":"Grand Enchanter Fiona",
	"genny":"Grey Warden Genevieve",
	"gg":"Gate Guardian",
	"go":"The Grand Oak",
	"goat":"Avvar Goat",
	"gtu":"Gaxkang the Unbound",
	"gotu":"Guardian of the Urn",
	"gou":"Guardian of the Urn",
	"gwa":"Grey Warden Alistair",
	"gwb":"Grey Warden Bethany",
	"gwc":"Grey Warden Carver",
	"gwg":"Grey Warden Genevieve",
	"gwm":"Grey Warden Mage",
	"gwo":"Grey Warden Oghren",
	"gwr":"Grey Warden Rogue",
	"gwv":"Grey Warden Velanna",
	"gww":"Grey Warden Warrior",
	"hd":"High Dragon",
	"ho":"Harvester Orsino",
	"hoda":"Heroes of Dragon Age",
	"hsa":"High Seeker Aldren",
	"ig":"Inferno Golem",
	"ign":"in-game name",
	"isa":"Isabela",
	"jowan":"Apostate Jowan",
	"ka":"King Alistair",
	"kc":"King Cailan",
	"kcc":"Knight Captain Cullen",
	"kcm":"Knight Commander Meredith",
	"ke":"King Endrin Aeducan",
	"kea":"King Endrin Aeducan",
	"km":"Keeper Marethari",
	"kol":"Kolgrim",
	"lc":"Large Creature",
	"le":"Lord Erimond",
	"leo":"Leopold",
	"lf":"Lyrium Fenris",
	"lmt":"Loghain Mac Tir",
	"lotf":"Lady of the Forrest",
	"lph":"Lord Pyral Harrowmont",
	"lsl":"Lay Sister Leliana",
	"mare":"Keeper Marethari",
	"maric":"King Maric",
	"moori":"Morrigan",
	"mori":"Morrigan",
	"morri":"Morrigan",
	"na":"Nightmare Aspect",
	"nats":"\"Naturals\": using time refills of stamina in PVP (i.e. not spending gems)",
	"nh":"Nathaniel Howe",
	"node":"Any place to click on in a quest to fight PvE including challenges",
	"nsoh":"Noble Spirit of Hope",
	"nsoj":"Noble Spirit of Justinia",
	"nug":"can be a Nug of any type or refer to an easy unit used for nugging",
	"nugging":"putting a \"nug team\" (easy team) in your defense (first) slot",
	"oc":"Ogre Commander",
	"op":"\"over-powered\": a hero considered so strong it threatens the balance of the game",
	"pba":"Prince Bhelen Aeducan",
	"pc":"Paragon Caridin",
	"pd":"Pride Demon",
	"psv":"Prince Sebastian Vale",
	"pve":"Player vs. Environment (consumes Energy)",
	"pvp":"Player vs. Player (consumes Stamina)",
	"qa":"Queen Anora",
	"qotbm":"Queen of the Blackmarsh",
	"rla":"Red Lyrium Archer",
	"rlm":"Red Lyrium Meredith",
	"rng":"Random Number Generator (how they determine what drops)",
	"ro":"Risen Ogre",
	"rs":"Ruby Shale",
	"saar":"Saarebas",
	"sam":"Samson",
	"sc":"Seeker Cassandra",
	"schmoo":"Schmooples",
	"sd":["Sophia Dryden","Sloth Demon"],
	"sg":"Steel Golem",
	"sh":"Sky Horror",
	"soh":"Spirit of Hope",
	"soj":"Spirit of Justinia",
	"sotb":"Sten of the Beresaad",
	"spal":"Ser Pounce A Lot",
	"sn":"Sister Nightingale",
	"snug":"Snug the Bronto",
	"ss":["Ser Stroud", "Sentinel Spellbinder"],
	"sta":"Sten\, the Arishok",
	"sten":"Sten\, the Arishok",
	"sw":"Shah Wyrd",
	"tam":"Tevinter Arcane Mage",
	"tb":"The Baroness",
	"tc":"Templar Carver",
	"tf":"The First",
	"tgo":"The Grand Oak",
	"tlm":"Tevinter Laetan Mage",
	"too":"The Old One",
	"toon":"\"cartoon\": a generic name for any of your characters",
	"uc":["Undead Challenge","Uncommon (rarity)"],
	"ul":"Ultra-legendary (rune)",
	"uld":"Uldred",
	"uncle":"Uldred",
	"va":"Vengeance Anders",
	"vart":"Varterral",
	"vh":"Very Hard (a difficulty on the Nexus)",
	"vt":"Varric Tethrasd",
	"wcd":"Warden Commander Duncan",
	"wf":"Witherfang"
};

$.popline.addButton({
	hoda: {
      	mode: "view",
      	action: function(event) {
        	var url = "https://www.google.com/search?q=heroes+of+dragon+age+" + encodeURIComponent($.popline.utils.selection().text());
        	window.open(url);
      	},
      	dynamicText: {
      		defaultText: "(not found - click to search)",
      		map: function (input) {	
      			var result = data[input.toLowerCase()];
				if (result && result.constructor === Array) {
					return result.join (" or ");
				}
				
				return result;
			}
		}
    }
});
